import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./Providers";
import NavbarLayout from "../components/layout/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const bgImage = "images/background.png";
  const bgStyle = { backgroundImage: `url(${bgImage})` };
  return (
    <html lang="en" className="dark ">
      <body className={inter.className}>
        <main style={bgStyle} className="min-h-[200vh] bg-cover bg-center">
          <NavbarLayout />
          <Providers>{children}</Providers>
        </main>
      </body>
    </html>
  );
}
